[app]
name = "Rust API"
key = "your-secret-key" # Should be a strong random key
url = "http://127.0.0.1:8080"
debug = false

[server]
addrs = "127.0.0.1:8080"

[database]
url = "mysql://root:123456@127.0.0.1:3306/rust_api"

[redis]
url = "redis://127.0.0.1:6379"

[jwt]
secret = "your-secret-key"
expires_in = 12